const LOCATIONS = [
  {
    city: "Charlottesville",
    population: 48117,
    state: "Virginia",
    mayor: "Nikuyah Walker (I)",
    governor: "Ralph Northam (D)",
    statebird: "Northern Cardinal",
  },
  {
    city: "Greenfield",
    population: 17456,
    state: "Massachusetts",
    mayor: "Roxann Wedegartner (D)",
    governor: "Charlie Baker (R)",
    statebird: "Black-Capped Chickadee",
  },
  {
    city: "San Angelo",
    population: 100215,
    state: "Texas",
    mayor: "Brenda Gutner (R)",
    governor: "Greg Abbott (R)",
    statebird: "Northern Mockingbird",
  },
  {
    city: "San Antonio",
    population: 1493000,
    state: "Texas",
    mayor: "Ron Nirenberg (D)",
    governor: "Greg Abbott (R)",
    statebird: "Northern Mockingbird",
  },
  {
    city: "Seattle",
    population: 744955,
    state: "Washington",
    mayor: "Jenny Durkan (D)",
    governor: "Jay Inslee (D)",
    statebird: "Willow Goldfinch",
  },
  {
    city: "Lakeshire",
    population: 1397,
    state: "Missouri",
    mayor: "Tim Seher (N/A)",
    governor: "Mike Parson (R)",
    statebird: "Eastern Bluebird",
  },
  {
    city: "Alice",
    population: 18887,
    state: "Texas",
    mayor: "Jolene B. Vanover (N/A)",
    governor: "Greg Abbot (R)",
    statebird: "Northern Mockingbird",
  },
  {
    city: "Austin",
    population: 964254,
    state: "Texas",
    mayor: "Steve Adler (D)",
    governor: "Greg Abbot (R)",
    statebird: "Northern Cardinal",
  },
  {
    city: "Baton Rouge",
    population: 221599,
    state: "Louisiana",
    mayor: "Sharon Weston Broome (D)",
    governor: "John Bel Edwards (D)",
    statebird: "Brown Pelican",
  },
  {
    city: "Boston",
    population: 694583,
    state: "Massachusetts",
    mayor: "Marty Walsh (D)",
    governor: "Charlie Baker (R)",
    statebird: "Black-Capped Chickadee",
  },
  {
    city: "Bristol",
    population: 26881,
    state: "Tennessee",
    mayor: "Margaret Feierabend",
    governor: "Bill Lee (R)",
    statebird: "Northern Mockingbird",
  },
  {
    city: "Goshen",
    population: 33566,
    state: "Indiana",
    mayor: "Jeremy Stutsman (D)",
    governor: "Eric Holcomb (R)",
    statebird: "Northern Cardinal",
  },
  {
    city: "Madison",
    population: 11879,
    state: "Indiana",
    mayor: "Bob Courtney (R)",
    governor: "Eric Holcomb (R)",
    statebird: "Northern Cardinal",
  },
  {
    city: "Philadelphia",
    population: 1584000,
    state: "Pennsylvania",
    mayor: "Jim Kenney (D)",
    governor: "Tom Wolf (F)",
    statebird: "Ruffed Grouse",
  },
  {
    city: "Rapid City",
    population: 75443,
    state: "South Dakota",
    mayor: "Steve Allender (R)",
    governor: "Kristi Noem (R)",
    statebird: "Ring-Necked Pheasant",
  },
];
